name: TheHaunted
version: 1.1
main: de.daricari.thehaunted.TheHaunted
author: DariCari
description: 

api-version: 1.13
 
commands:
  thehaunted:
    usage: /<command>
    description: Admin command
  start:
    usage: /<command>
    description: Admin command